-- First Task
CREATE TABLE PLAYER(
    ID NUMBER NOT NULL UNIQUE ,
    NAME VARCHAR(255) UNIQUE ,
    AGE NUMBER
);

CREATE TABLE MANAGER(
    ID NUMBER NOT NULL ,
    NAME VARCHAR(255) ,
    SALARY NUMBER ,
    UNIQUE (ID,NAME)
);

CREATE TABLE MANAGER(
    ID NUMBER NOT NULL ,
    NAME VARCHAR(255) ,
    AGE NUMBER ,
    PRIMARY KEY (ID)
);

-- Second Task
